name: Docker

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 1 * * *'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Docker Buildx and publish
        uses: ilteoood/docker_buildx@master
        with:
          imageName: rsaikali/mqtt-listener
          platform: linux/amd64,linux/arm/v7
          dockerHubUser: ${{ secrets.DOCKER_HUB_LOGIN }}
          dockerHubPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}
          publish: true
